version: '3.8'

services:
  nodejs:
    container_name: api-shortener
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
    command: sh -c "npm run start:dev"
