version: '3.8'

services:
  nodejs:
    container_name: api-shortener
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c "npm run start:docker"

  postgres:
    container_name: shortener_db
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: