apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-statefulset
    env: dev
spec:
  selector:
    app: postgres-statefulset
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
